name: Reproduce ASAN crash
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  compile-and-run:
    runs-on: ubuntu-latest
    container:
      image: smatchcube/reproduce_asan_crash
    name: ${{ matrix.config.name }}
    strategy:
      matrix:
        config:
          - {
              name: "Without ASAN",
              with_ASAN: "NO",
            }
          - {
              name: "With ASAN",
              with_ASAN: "YES",
            }
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          cmake --warn-uninitialized \
                -DWITH_ASAN="${{ matrix.config.with_ASAN }}" \
                -S . -B build/
      - name: Build
        run: cmake --build build/
      - name: Run
        run: ./build/reproduce_ASAN_crash
